# This is a basic workflow to help you get started with Actions

name: Python CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 3,8,9,12,15 * * *'
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install beautifulsoup4

      - name: Run main.py 
        run: |
          python main.py
          
#      - name: Commit and Push
#        run: |
#          git add -N .
#          if ! git diff --exit-code --quiet
#          then
#            git config user.name "kazukios actions"
#            git config user.email "actions@gmail.com"
#            git add .
#            git commit -m "update yahoo news csv"
#            git pull
#            git push origin master
#          fi
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deploy
        env:
          TO_S: ${{ secrets.TO_S }}
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete csv/ $TO_S